# Asignamos los valores para la conectar a la DB
spring:
  jpa:
    hibernat:
      ddl-auot: update
      propeties:
      hibernate:
        dialect: org.hibernate.dialect.H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:\Users\PERSONAL\Desktop\base\Prueba
    username: root
    password: root